litreview/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from followers import views as follower_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('following/', follower_views.following, name='following'),
    path('unfollowing/<user>/', follower_views.unfollowing, name='unfollowing'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('reviews.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path('', views.feed, name='review-home'),
    path('posts/', views.posts, name='post-home'),
    path('reviews/new/', views.create_review, name='review-create'),
    path('tickets/new/', views.create_ticket, name='ticket-create'),
    path('reviews/<int:pk>/update/', views.update_review, name='review-update'),
    path('tickets/<int:pk>/update/', views.update_ticket, name='ticket-update'),
    path('reviews/<int:pk>/delete/', views.delete_review, name='review-delete'),
    path('tickets/<int:pk>/delete/', views.delete_ticket, name='ticket-delete'),
    path('tickets/answer/<int:pk>/', views.answer_ticket, name='ticket-answer'),
    path('tickets/response/<int:pk>', views.response_ticket, name='ticket-response'),
]

reviews/models.py
from PIL import Image
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to='books_img')
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    if image is True:
        def save(self, *args, **kwargs):
            super(Ticket, self).save(*args, **kwargs)
            img = Image.open(self.image.path)
            if img.height > 200 or img.width > 125:
                output_size = (200, 125)
                img.thumbnail(output_size)
                img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('ticket-detail', kwargs={'pk': self.pk})


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    headline = models.CharField(max_length=128)
    body = models.TextField(max_length=8192, blank=True)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

    def get_absolute_url(self):
        return reverse('review-detail', kwargs={'pk': self.pk})

reviews/forms.py
from django import forms
from .models import Ticket, Review


class CreateTicket(forms.ModelForm):
    title = forms.CharField(max_length=128, widget=forms.TextInput)
    description = forms.CharField(max_length=2048, widget=forms.Textarea(), required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'image']


class CreateReview(forms.ModelForm):
    headline = forms.CharField(max_length=128, widget=forms.TextInput())
    rating = forms.ChoiceField(initial=1, widget=forms.RadioSelect(), choices=((1, "★"), (2, "★★"), (3, "★★★"), (4, "★★★★"), (5, "★★★★★")))
    body = forms.CharField(max_length=8192, widget=forms.Textarea(), required=False)

    class Meta:
        model = Review
        fields = ['headline', 'rating', 'body']

reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import CharField, Value
from django.core.exceptions import PermissionDenied
from itertools import chain
from .models import Ticket, Review
from .forms import CreateTicket, CreateReview
from followers.models import UserFollows


@login_required
def feed(request):
    # get all followed user
    f_users = []
    u_followed = UserFollows.objects.filter(user=request.user)
    for u_follow in u_followed:
        f_users.append(u_follow.followed_user)

    # to ask about
    f_user_me = f_users
    f_user_me.append(request.user)
    tickets = Ticket.objects.filter(user__in=f_users).order_by("-time_created")
    tickets = tickets.annotate(content_type=Value("TICKET", CharField()))
    reviews = Review.objects.filter(user__in=f_users).order_by("-time_created")
    reviews = reviews.annotate(content_type=Value("REVIEW", CharField()))
    visible_feeds = sorted(chain(tickets, reviews), key=lambda visible_feeds: visible_feeds.time_created, reverse=True)
    context = {'visible_feeds': visible_feeds, 'f_users': f_users}
    return render(request, "reviews/home.html", context)


@login_required
def posts(request):
    own_tickets = Ticket.objects.filter(user=request.user).order_by("-time_created")
    own_tickets = own_tickets.annotate(content_type=Value("TICKET", CharField()))
    own_reviews = Review.objects.filter(user=request.user).order_by("-time_created")
    own_reviews = own_reviews.annotate(content_type=Value("REVIEW", CharField()))
    own_posts = sorted(chain(own_tickets, own_reviews), key=lambda own_posts: own_posts.time_created, reverse=True)
    return render(request, 'reviews/posts.html', {'own_posts': own_posts})


@login_required
def create_ticket(request):
    if request.method == 'POST':
        t_form = CreateTicket(request.POST, request.FILES)
        if t_form.is_valid():
            ticket = t_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            return redirect('reviews:review-home')
    else:
        t_form = CreateTicket()
    context = {'t_form': t_form, 'task': 'Create'}
    return render(request, 'reviews/ticket_form.html', context)


@login_required
def create_review(request):
    if request.method == 'POST':
        t_form = CreateTicket(request.POST, request.FILES)

        if t_form.is_valid():
            ticket = t_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            r_form = CreateReview(request.POST)
            if r_form.is_valid:
                review = r_form.save(commit=False)
                review.ticket = ticket
                review.user = request.user
                review.save()
            return redirect('reviews:review-home')
    else:
        t_form = CreateTicket()
        r_form = CreateReview()

    context = {'t_form': t_form, 'r_form': r_form, 'task': 'Create'}
    return render(request, 'reviews/review_form.html', context)


@login_required
def response_ticket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    if request.method == 'POST':
        r_form = CreateReview(request.POST)

        if r_form.is_valid:
            review = r_form.save(commit=False)
            review.ticket = ticket
            review.user = request.user
            review.save()
        return redirect('reviews:review-home')
    else:
        r_form = CreateReview()

    context = {'r_form': r_form, 'ticket': ticket}
    return render(request, 'reviews/review_form.html', context)


@login_required
def update_ticket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    if ticket.user != request.user:
        raise PermissionDenied()

    if request.method == "POST":
        t_form = CreateTicket(request.POST, request.FILES, instance=ticket)
        if t_form.is_valid():
            t_update = t_form.save(commit=False)
            t_update.user = request.user
            t_update.save()
            return redirect("/")
    else:
        t_form = CreateTicket(instance=ticket)
    context = {"t_form": t_form, 'task': 'Update'}
    return render(request, "reviews/ticket_form.html", context)


@login_required
def update_review(request, pk):
    review = Review.objects.get(id=pk)
    if review.user != request.user:
        raise PermissionDenied()

    if request.method == "POST":
        r_form = CreateReview(request.POST, request.FILES, instance=review)
        if r_form.is_valid():
            r_update = r_form.save(commit=False)
            r_update.user = request.user
            r_update.save()
            return redirect("/")
    else:
        r_form = CreateReview(instance=review)
    context = {"r_form": r_form, "ticket": review.ticket, 'task': 'Update'}
    return render(request, "reviews/review_form.html", context)


@login_required
def delete_ticket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    if request.user == ticket.user:
        ticket.delete()
    return redirect("reviews:review-home")


@login_required
def delete_review(request, pk):
    review = Review.objects.get(id=pk)
    if request.user == review.user:
        review.delete()
    return redirect("reviews:review-home")


@login_required
def answer_ticket(request, pk):
    ticket = Ticket.objects.get(id=pk)
    if request.method == "POST":
        r_form = CreateReview(request.POST)
        if r_form.is_valid():
            review = r_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()
            return redirect("reviews:review-home")
    else:
        r_form = CreateReview()
    context = {"r_form": r_form, "ticket": ticket}
    return render(request, "reviews/review_form.html", context)

reviews/templates/reviews/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'reviews/main.css' %}">

    <title>LITREVIEW</title>

</head>
<body>
  <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'reviews:review-home' %}">LITReview</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto"></div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'reviews:review-home' %}">Feed</a>
                <a class="nav-item nav-link" href="{% url 'reviews:post-home' %}">Posts</a>
                <a class="nav-item nav-link" href="{% url 'following' %}">Following</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout ({{ user.username }})</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

reviews/templates/reviews/home.html
{% extends "reviews/base.html" %}
{% block content %}
          <div class="container">
            <div class="row">
              <div class="col">
                <a type="button" class="btn btn-outline-primary mb-3 form-control btn-block" href="{% url 'reviews:ticket-create' %}">Request a Review</a>
              </div>
              <div class="col">
                <a type="button" class="btn btn-outline-primary mb-3 form-control btn-block" href="{% url 'reviews:review-create' %}">Post a Review</a>
              </div>
            </div>
          </div>
{% if not visible_feeds %}
    <div class="row d-flex justify-content-center py-2">
        <p class="font-weight-bold">You need to follow someone first or people you follow have not written anything yet!</p>
    </div>
{% endif %}

{% for feed in visible_feeds %}
  {% if feed.content_type == "TICKET" %}
    {% include 'reviews/ticket_snippet.html' %}
  {% endif %}
  {% if feed.content_type == "REVIEW" %}
    {% include 'reviews/review_snippet.html' %}
  {% endif %}
{% endfor %}

{% endblock content %}

reviews/templates/reviews/posts.html
{% extends "reviews/base.html" %}
{% block content %}
<h3 class="text-center">Your Posts</h3>
{% if not own_posts %}
    <div class="row d-flex justify-content-center py-2">
        <p class="font-weight-bold">You need to request a review or post a review first!</p>
    </div>
{% endif %}

{% for feed in own_posts %}
  {% if feed.content_type == "TICKET" %}
    {% include 'reviews/ticket_snippet.html' %}
  {% endif %}
  {% if feed.content_type == "REVIEW" %}
    {% include 'reviews/review_snippet.html' %}
  {% endif %}
{% endfor %}

{% endblock content %}

reviews/templates/reviews/review_detail.html
{% extends "reviews/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <p>
          <span class="text-primary font-weight-bold">{{ review.user }}</span>
          <span>posted on {{ review.time_created|date:"F d, Y" }}</span>
        </p>
        {% if review.user == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'reviews:review-update' review.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'reviews:review-delete' review.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ review.headline }}</h2>
      <p class="article-content">{{ review.body }}</p>
    </div>
  </article>
{% endblock content %}

reviews/templates/reviews/review_form.html
{% extends "reviews/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <legend class="border-bottom mb-4 text-center">
            {% if not task %}
                Create a Review
            {% else %}
                {{ task }} a Review
            {% endif %}
        
        </legend>
        <form method="POST" enctype='multipart/form-data'>
            <fieldset class="form-group">
            {% csrf_token %}
            {% if request.get_full_path == "/reviews/new/" %}
                <h3>Book / Article</h3>
                {{ t_form|crispy }}
            {% else %}
            <h5>You are posting in response to</h5>
            <div class="media content-section">
                <div class="media-body">
                      <p class="border-bottom"><span class="text-primary font-weight-bold">{{ ticket.user }}</span>
                          <span><small class="text-muted">posted on {{ ticket.time_created|date:"F j, Y, g:i a" }} this ticket</small></span>
                        </p>
                        <div class="box text-center">
                            <h5 class="font-weight-bold">{{ ticket.title }}</h5>
                        </div>
                        <div class="container pt-3">
                            <div class="row">
                              <div class="col flex-grow-0 px-1">
                                {% if ticket.image %}
                                    <img class="img-thumbnail float-left mb-1 mr-3" src="{{ ticket.image.url }}" width="125" height="200">
                                {% endif %}
                                <div class="text-justify">
                                    {{ ticket.description }}
                                </div>
                              </div>
                            </div>
                        </div>
                </div>
            </div>
            {% endif %}
            
            <h3 class="border-top mt-4">Review</h3>
            {{ r_form|crispy }}
            </fieldset>
            <div class="form-group text-right">
                <a class="btn btn-danger" href="{% url 'reviews:review-home' %}">Cancel</a>
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

reviews/templates/reviews/review_snippet.html
<div class="media content-section">
  <div class="media-body">
    <p class="border-bottom">
      <span class="text-primary font-weight-bold">
        {% if feed.user == user %}
          You
        {% else %}
          {{ feed.user }}
        {% endif %}
      </span>
      <span>
        <small class="text-muted">posted a review on {{ feed.time_created|date:"F j, Y, g:i a" }}</small>
      </span>
      {% if feed.user == user %}
        <span class="float-right">
          <a class="text-primary" href="{% url 'reviews:review-update' feed.id %}">Update</a>
          <a class="ml-2 text-danger" href="{% url 'reviews:review-delete' feed.id %}">Delete</a>
        </span>
      {% endif %}
    </p>
    <div class="box text-center">
      <h5 class="font-weight-bold">{{ feed.headline }}</h5>
    </div>
    <div class="container pt-3">
      <div class="row">
        <div class="col flex-grow-0 px-1">
          <div class="text-justify">
            {{ feed.body }}
          </div>
          <div class="box pt-2">
            <h5>Rating: {{ feed.rating }}★</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="border rounder 3px bg-light mt-4 pl-3 pr-3 py-2">
      <p class="border-bottom">
        <span class="text-primary font-weight-bold">
          {% if feed.ticket.user == user %}
            You
          {% else %}
            {{ feed.ticket.user }}
          {% endif %}
        </span>
        <span>
          <small class="text-muted">requested a review on {{ feed.ticket.time_created|date:"F j, Y, g:i a" }}</small>
        </span>
        {% if feed.user != user %}
          {% if feed.ticket.user == user %}
            <span class="float-right">
              <a class="text-primary" href="{% url 'reviews:ticket-update' feed.ticket.id %}">Update</a>
              <a class="ml-2 text-danger" href="{% url 'reviews:ticket-delete' feed.ticket.id %}">Delete</a>
            </span>
          {% endif %}
        {% endif %}
      </p>
      <div class="box text-center">
        <h5 class="font-weight-bold">{{ feed.ticket.title }}</h5>
      </div>
      <div class="container pt-3">
        <div class="row">
          <div class="col flex-grow-0 px-1">
            {% if feed.ticket.image %}
              <img class="img-thumbnail float-left mb-1 mr-3" src="{{ feed.ticket.image.url }}" width="125" height="200" alt="{{ feed.ticket.title }}">
            {% endif %}
            <div class="text-justify">
              {{ feed.ticket.description }}
            </div>
            <!-- {% if feed.ticket.review_set.all %} -->
              {% if feed.user != user %}
                <div class="text-right">
                  <a class="btn btn-primary" href="{% url 'reviews:ticket-response' feed.ticket.pk %}">Post a review</a>
                </div>
              {% endif %}
            <!-- {% endif %} -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

reviews/templates/reviews/ticket_detail.html
{% extends "reviews/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.user }}</a>
        <small class="text-muted">{{ object.time_created|date:"F d, Y" }}</small>
        {% if object.user == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'reviews:ticket-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'reviews:ticket-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.description }}</p>
      {% if object.image %}
      <div class="col flex-grow-0 px-1">
          <img src="{{ object.image.url }}"/>
      </div>
  {% endif %}
    </div>
    <div class="btn float-right">
      <a type="button" class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'reviews:ticket-answer' object.id %}">
        {% if object.user == user %}
          Reply to your Ticket
        {% else %}
          Write Review in response to {{ object.user }}
        {% endif %}
      </a>
    </div>
  </article>
{% endblock content %}

reviews/templates/reviews/ticket_form.html
{% extends "reviews/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center">{{ task }} a Ticket</legend>
                {{ t_form|crispy }}
            </fieldset>
            <div class="form-group text-right">
                <a class="btn btn-danger" href="{% url 'reviews:review-home' %}">Cancel</a>
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

reviews/templates/reviews/ticket_snippet.html
<div class="media content-section">
  <div class="media-body">
    <p class="border-bottom">
      <span class="text-primary font-weight-bold">
        {% if feed.user == user %}
          You
        {% else %}
          {{ feed.user }}
        {% endif %}
      </span>
      <span>
        <small class="text-muted">requested a review on {{ feed.time_created|date:"F j, Y, g:i a" }}</small>
      </span>
      {% if feed.user == user %}
        <span class="float-right">
          <a class="text-primary" href="{% url 'reviews:ticket-update' feed.id %}">Update</a>
          <a class="ml-2 text-danger" href="{% url 'reviews:ticket-delete' feed.id %}">Delete</a>
        </span>
      {% endif %}
    </p>
    <div class="box text-center">
      <h5 class="font-weight-bold">{{ feed.title }}</h5>
    </div>
    <div class="container pt-3">
      <div class="row">
        <div class="col flex-grow-0 px-1">
          {% if feed.image %}
            <img class="img-thumbnail float-left mb-1 mr-3" src="{{ feed.image.url }}" width="125" height="200" alt="{{ feed.title }}">
          {% endif %}
          <div class="text-justify">
            {{ feed.description }}
          </div>
        </div>
      </div>
    </div>
    <div>
      {% if not feed.review_set.all %}
        <div class="text-right">
          <a class="btn btn-primary" href="{% url 'reviews:ticket-response' feed.pk %}">Post a review</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>